### ISSUE TITLE
Missing main information in documentation : defaut host address is 127.0.0.1

### ISSUE THREAD

**Issue by pedefe** [Pithikos/python-websocket-server#10]
Hello,
Main page documentation forgets a main information : default host address filter is 127.0.0.1.
Then, trying to use your powerfull webSocketServer between my PC and a RaspBerry Pi, i need to look in code to understand that defaut host filter was 127.0.0.1, so from local development.
I think it will be very helpfull to complete your main page with this information, and to give a small information about this parameter for other configuration :
self._server = WebsocketServer(self._iPort, "127.0.0.1")
or
self._server = WebsocketServer(self._iPort, "")

Best regards.

**Comment by Pithikos** [comment]
Thanks for the feedback @pedefe and apologies for being late. The documentation has been altered a few times and now it should reflect more the things you mention: https://github.com/Pithikos/python-websocket-server/blob/master/README.md

If you think that still something is missing, feel free to open an issue again.

Cheers!
