### ISSUE TITLE
Add python-websockets-server to the cheese shop

### ISSUE THREAD

**Issue by brejoc** [Pithikos/python-websocket-server#2]
How about adding python-websockets-server to the cheese shop? I could try to assist you with the setup.py if you are interested.

**Comment by Pithikos** [comment]
I am not sure how this would be helpful. I made this with the intention that someone can simply include it in their project without having to install third dependencies. Making it part of pip would defeat the purpose.

There are already many many projects at the pypi that someone can use like [tornado](http://www.tornadoweb.org).

**Comment by brejoc** [comment]
Well, there are two things to consider:

1. Having the project on pypi makes it more visible and thus gain popularity.
2. There are several ways of including the server, which I don't have to tell you. Loading it from pypi via `pip` or something else might be one of them and isn't preventing anyone from including it directly. So you only opened up one more (fairly standard) way to include the project.

**Comment by Pithikos** [comment]
Hi, I might do this in the future. However I first will have to make more tests. For example the module doesn't work on Chromium for me..

**Comment by Pithikos** [comment]
Hi brejoc,

I worked out  the few bugs that were there and now I have added some info on [PIP](https://pypi.python.org/pypi/websocket-server). If you have the time I would be grateful if you can make the `setup.py`. If not then I will work on it in the next weeks whenever I find some free time.

**Comment by brejoc** [comment]
Sorry @Pithikos, I'm very busy at the moment. But hopefully I can take care of this next weekend.

**Comment by brejoc** [comment]
With pull request #4 we've got a first draft for the setup.py

**Comment by Pithikos** [comment]
Ok, You can now use `pip install websocket-server`.

Cheers!

**Comment by brejoc** [comment]
Awesome! :)
