### ISSUE TITLE
Allow server termination when running in forever mode

### ISSUE THREAD

**Issue by ankitmcgill** [Pithikos/python-websocket-server#23]
Provide method to let user program to terminate websocket server when the socket server is executing run_forever() function.

**Comment by kirkatexo** [comment]
This seems to conflict with traditional usage of *run_forever()* as a blocking listen-initialization. What if there was 1) an alternative "run_threaded()" method (see #30 ) and 2) a "terminate()" method for those cases?

**Comment by mithom** [comment]
i agree here, there should be a possibility for gracefull shutdown, quitting the server either from in a callback function or from outside in cuse you use threaded. No need to forsee a run_threaded() function here as the Threading module is exactly meant for this and it would only complicate stuff to prevent 2 lines of code.

**Comment by Pithikos** [comment]
Related: https://github.com/Pithikos/python-websocket-server/issues/72

**Comment by Pithikos** [comment]
This is now supported with v0.5.4
