### ISSUE TITLE
WebSocketHandler.handshake strips \r\n from the recv'd message, then looks for \r\n

### ISSUE THREAD

**Issue by CMTaylor** [Pithikos/python-websocket-server#27]
I'm not sure why this message is being "strip"ped, but it messes up the key regular expression since the terminating \r\n is stripped off and the re.search will ALWAYS fail if the Sec-WebSocket-Key message is the last line in the handshake sequence:
    key = re.search('\n[sS]ec-[wW]eb[sS]ocket-[kK]ey[\s]*:[\s]*(.*)\r\n', message)

**Comment by CMTaylor** [comment]
My somewhat kludgy fix is to put the terminating \r\n back on message after stripping it.

**Comment by CMTaylor** [comment]
@Pithikos Any chance of getting the PR for this merged into your master?

**Comment by AndyLee1024** [comment]
change ` message = self.request.recv(1024).decode().strip()` to `        message = self.request.recv(2048).decode().strip()`

**Comment by Pithikos** [comment]
Fixed with c3f0b00fbd29e478b814b4ea32b0b7d479e89841
