### ISSUE TITLE
 How to close the connection?

### ISSUE THREAD

**Issue by wangjian8006** [Pithikos/python-websocket-server#38]

**Comment by Pithikos** [comment]
You mean the server? You can use `self.shutdown()` or `self.server_close`. Probably in the future there will be a shortcut as part of the API.

**Comment by wangjian8006** [comment]
The client is shut down by the server.

**Comment by wangjian8006** [comment]
The client is shut down by the server,will happen error.

**Comment by Pithikos** [comment]
Not sure what you mean. Please try to elaborate and I will try to have a look at it.
