### ISSUE TITLE
Handle ping/pong frames.

### ISSUE THREAD

**Issue by duskCoder** [Pithikos/python-websocket-server#5]
I am having some issues with certain browsers (mainly on embedded devices) that send ping (opcode 0x09) and/or pong (opcode 0x0A) frames without being solicited.

With the current implementation, those frames are handled like any text message (opcode 0x01) and there is no way to differenciate them from actual messages. The only workaround I found is to check if the payload of the frame matches a specific text (e.g. "PING"). IMHO the solution is rather unclean. 

I am thinking of two ways to deal with the issue:
- either make the server automatically send a pong frame whenever it receives a ping frame and not call the callback message_received()
- add another callback which is called when a ping frame is received and let the user deal with it.

I can probably help with the code if needed.

Thank you by advance for reading :)

**Comment by Pithikos** [comment]
You are right. A major problem is that I don't actually check for the OPCODE of any message received except for a CLOSE_CONN opcode. There should be a warning or something when a non-supported OPCODE arrives (in this case PONG).

As about implementation I think what makes sense (at least to me) is to check if the opcode is PING in `message_received()`. Then a `send_pong()` method needs to be implemented which just sends the pong response. In that way things are kept quite simple and intuitive.

Feel free to implement it if you want. I am jobless atm so I have no time to do any changes unfortunately.. If the implementation works fine and is consistent with the rest of the code, I can merge it.
