### ISSUE TITLE
Server crashed when connection lost

### ISSUE THREAD

**Issue by neednam** [Pithikos/python-websocket-server#57]
I write simple client for android on java. Inside applet web-client based on client.html from your source.
When i clossed applet, server crashed with error:

Listening on port 9000 for clients..
New client connected and was given id 1                     Client(1) disconnected                                      ----------------------------------------                    Exception happened during processing of request from ('127.0.0.1', 58142)                                               Traceback (most recent call last):                            File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/SocketServer.py", line 596, in process_request_thread                                                    self.finish_request(request, client_address)              File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/SocketServer.py", line 331, in finish_request                                                            self.RequestHandlerClass(request, client_address, self)   File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 136, in __init__                               StreamRequestHandler.__init__(self, socket, addr, server)                                                             File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/data/user/0/ru.iiec.pydroid/files/arm-linux-androideabi/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
ValueError: need more than 0 values to unpack
----------------------------------------

**Comment by Dancger** [comment]
Had the same problem with the pip package (installation 1). After a reinstall with the github code (installation 2) the problem was gone. Its worth a shot.
