### ISSUE TITLE
Opcode checking needed

### ISSUE THREAD

**Issue by Pithikos** [Pithikos/python-websocket-server#6]
After the [report from duskCoder](https://github.com/Pithikos/python-websocket-server/issues/5) it became apparent that no opcode checking is implemented atm. This can be problematic since the user doesn't get any information on PING/PONG for example.

OPCODE checking needs to be implemented in `message_received()` and an appropriate warning needs to be outputted to the user in case of an **unknown** or **unsupported** OPCODE.

**Comment by duskCoder** [comment]
And not sure if you really meant to implement the opcode checking in ```message_received()```, a callback provided by the developer or ```read_next_message()```, where you already check the CLOSE_CONN.

If we let the developer handle this, the only thing we have to do is to add the OPCODE to the arguments given to ```message_received()```. This is very straightforward to implement but in this case, we won't be able to issue a warning on unknown OPCODE (it will be the developer's reponsibility also) without double-checking.

Is this an issue in your opinion @Pithikos ?

**Comment by Pithikos** [comment]
Oops, my mistake. I did indeed meant `read_next_message()`. What makes sense to me is that in `read_next_message()` will do all the evaluation etc. of a received message. Then depending on what message was received a different action has to be made (print warning, read payload, send pong, etc.). Ofcourse the best way would be if every action it's just a separate method just for the sake of modularity.
