### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Yhangzzz** [Pithikos/python-websocket-server#73]
Hello, I found that the library does not support Chinese in use. I can't receive it correctly when receiving Chinese. In the read_next_message(self) function, str() should be used instead of chr() when decoding.

`decoded = bytearray()
	for char in self.read_bytes(payload_length):
		char ^= masks[len(decoded) % 4]
		decoded.append(char)
	decoded = str(decoded, encoding="utf-8")
	self.server._message_received_(self, decoded)`

**Comment by Pithikos** [comment]
Related: https://github.com/Pithikos/python-websocket-server/issues/72

**Comment by rainbird** [comment]
> decoded = str(decoded, encoding="utf-8")

thk!

**Comment by Pithikos** [comment]
It's still unclear to me where in the code this goes. Feel free to post a more accurate snippet or make a PR. Closing for now.
