### ISSUE TITLE
Support with asyncio

### ISSUE THREAD

**Issue by applebee1558** [Pithikos/python-websocket-server#75]
Have this library work asynchronously, to make some aspects non-blocking, and for compability with other libraries.

**Comment by scoopgracie** [comment]
Hi, you might want to check out other libraries that do use asyncio. Perhaps https://github.com/aaugustin/websockets would work?

**Comment by applebee1558** [comment]
Ok I don’t even remember opening this issue since it’s so long ago, but thanks. I’ve used websockets for a long time now.

**Comment by Pithikos** [comment]
Hi, so the aim of this project is to fill the gap. Most websocket libraries use asyncio atm but there's good cases where a threaded library makes life easier (e.g. testing). So there's no plans to support asyncio.

HOWEVER
It's super easy to patch this library with `gevent` to get it working in an asyncio fashion.
