### ISSUE TITLE
server send message to client

### ISSUE THREAD

**Issue by lovewqf** [Pithikos/python-websocket-server#79]
How does the websocket server actively send messages to the client?

**Comment by jorgebg2016** [comment]
I wanna know too. I have the same problem than you. Do you got solution for that? If you got, could you say me?

**Comment by stanma9107** [comment]
WebSocket cannot send messages to client automatic, it need some action to trigger it.

**Comment by Pithikos** [comment]
An example is needed. This is too vague of a question. Closing.
