### ISSUE TITLE
Server address

### ISSUE THREAD

**Issue by aymangrais** [Pithikos/python-websocket-server#8]
I can see that server is initiated listening on port 127.0.0.1.. that would be inconvenient if we want to connect using a client on another IP of the network. Better to use address ANY (0.0.0.0) to listen on all network interfaces

**Comment by Pithikos** [comment]
That is true. I do mention it actually in the README (https://github.com/Pithikos/python-websocket-server#websocketserver).

The problem with setting the default IP to 0.0.0.0 is that it's a bit risky (similar to Windows having all ports open by default). Having 127.0.0.1 the default, covers most most usage cases and doesn't exhibit any security issues.
