### ISSUE TITLE
2nd or 3rd client happens onopen() is called very long time (more than 40 seconds) after open webpage or reload webpage.

### ISSUE THREAD

**Issue by howard-ht-liu** [Pithikos/python-websocket-server#84]
Hi,
I have a question: 2nd or 3rd client happens onopen() is called very long time (more than 40 seconds) after open webpage or reload webpage. During this long time, browser's loading icon always shows loading animation.
[Step to reproduce]
1. websocket_server: ubuntu 18.4.
2. first Android device's browser (chrome) open the page and reload many times. Util now, onopen() behaves normal.
3. 2nd or 3rd Android device's browser (chrome or safari) open the page and then happens onopen() is called very long time (more than 40 seconds) after open webpage or reload webpage.

Do you have any suggestion to it? 
Thanks.
Howard.

**Comment by Pithikos** [comment]
This seems like an issue outside the library. Closing
