### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by lefuturiste** [Pithikos/python-websocket-server#86]
If not, do we have forks ?

**Comment by Pithikos** [comment]
I'm not actively maintaining it atm. Might go through some minor PRs every now and then. But if someone wants to help out, I'd be happy to add people as collaborators.

**Comment by Ksengine** [comment]
improved fork pf this project
https://github.com/Ksengine/WSocket
i am created with WSGI support.

**Comment by Pithikos** [comment]
Update on this:

I'm including this project as part of some other projects so maintenance is more upbeat atm. So closing this for now.
