### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

### ISSUE THREAD

**Issue by lzcdawang** [Pithikos/python-websocket-server#88]
hi,This error often occurs when I implement a simple echo server,how to solve this problem

**Comment by rainbird** [comment]
这个是握手的问题,你的client发送的时候,结尾有问题

**Comment by newsbubbles** [comment]
any luck figuring this out?

**Comment by Pithikos** [comment]
Related: https://github.com/Pithikos/python-websocket-server/issues/72
