### ISSUE TITLE
How does the websocket_server accept long strings?

### ISSUE THREAD

**Issue by stevenXS** [Pithikos/python-websocket-server#89]
How do I set the maxMessageSize property

**Comment by mchuv** [comment]
HI, i'm having problems with strings larger than 64Kb, i solved it spliting the string in many messages.

**Comment by Pithikos** [comment]
@mchuv there's a test that covers that case. So unsure if maybe you use an older version?

https://github.com/Pithikos/python-websocket-server/blob/master/tests/test_message_lengths.py#L82

**Comment by mchuv** [comment]
> @mchuv there's a test that covers that case. So unsure if maybe you use an older version?
> 
> https://github.com/Pithikos/python-websocket-server/blob/master/tests/test_message_lengths.py#L82

Thank you for your answer, and congratulations for your library, it's the most simple and flexible (for my needs) option in python, i have test many,  the best of all is than i can use it inside a custom web server.
