### ISSUE TITLE
ValueError on Python 3.5.0 on every received message.

### ISSUE THREAD

**Issue by F1ashhimself** [Pithikos/python-websocket-server#9]
Got:

```
  File "...\lib\site-packages\websocket_server\websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
ValueError: not enough values to unpack (expected 2, got 0)
```

every time when message was received.

**Comment by Pithikos** [comment]
Thanks for reporting this.

What is the message you are trying to send and in what format? Clear text? ASCII? Unicode? Also is the server and the client the same machine?

**Comment by F1ashhimself** [comment]
@Pithikos , simple clear text message. The server and the client are on the same machine. Tried without any handlers, just start server, connect client to it and send message.

**Comment by Pithikos** [comment]
Some further questions:

1. Is this python2 or python3?
2. Did you `pip install` the websocket module or clone it from github?
3. Which browser do you use as client?
4. Could you provide some code snippet if possible? Or are you using the example from the project?

**Comment by F1ashhimself** [comment]
1. As I mention in title this about python 3.5.0
2. Installed from pypi
3. Python as client
4. example from project

**Comment by F1ashhimself** [comment]
Thank you, verified that problem is on client side.
